---
# tasks file for nginx
- include_tasks: install.yaml
- include_tasks: configure.yaml
- include_tasks: service.yaml
- name: status message
  shell: echo "nginx server upated at `date`" > /tmp/status_report.txt 
