---
# tasks file for apache
- debug:
    msg: "Installing apache2"
- include_tasks: install.yaml
- include_tasks: configure.yaml
- include_tasks: service.yaml
- name: status message
  shell: echo "apache server upated at `date`" > /tmp/status_report.txt
